### ISSUE TITLE
test data not unzip

### ISSUE THREAD

**Issue by gravitycyk** [facebookresearch/NeuralPassthrough#3]
hi, I not unzip test data, Do you kown how to get data?
Thanks~

**Comment by leixiao-ubc** [comment]
Hi, I'm not sure if I understand your question, but does it work when you go to the link https://github.com/facebookresearch/NeuralPassthrough/blob/main/data/test.zip and click the download button? I'll close the issue for now.

**Comment by gravitycyk** [comment]
> Hi, I'm not sure if I understand your question, but does it work when you go to the link https://github.com/facebookresearch/NeuralPassthrough/blob/main/data/test.zip and click the download button? I'll close the issue for now.

Thanks, I have solved the problem~because LFS
